stages:
  - pre-build
  - build
  - tests
  - report

base image:
  stage: pre-build
  tags:
    - test-finances-shell

  script:
    - docker build --tag selenium:base .docker/Base
    - docker build --tag selenium:nodebase .docker/NodeBase
    - docker build --tag selenium:nodechrome .docker/NodeChrome
  when: manual

application image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag application:latest --file .docker/application.Dockerfile .
  when: manual

.smoke:
  stage: tests
  image: application:latest
  services:
    - selenium:nodechrome
  tags:
    - test-finances-docker

  variables:
    APP_HOST: 'https://test-finances.404-group.info'
    DIRECT_CONNECT: 'false'

  script:
    - npm cache clear --force
    - /node_modules/protractor/bin/protractor conf.js --browser chrome --continue-on-error --disableChecks --capabilities.chromeOptions.args window-size=1920,1080 --suite create_user,add_accesses,create_services,cashier,regression --capabilities.chromeOptions.args headless

  after_script:
    - allure generate allure-results -o public --clean

  only:
    refs:
      - branches

  artifacts:
    paths:
      - public
    expire_in: 1 day
    when: always

  allow_failure: yes

smoke_test:
  extends: .smoke
  only:
    - master

smoke_test_triggers:
  extends: .smoke

pages:
  stage: report
  tags:
    - master
    - test-finances-docker

  only:
    - master

  script:
    - ""

  artifacts:
    paths:
      - public
    expire_in: 1 day

