test:
  image: "node_js"
  tags:
    - docker
  services:
    - vexorio/postgres:10-ip4r


  variables:
    POSTGRES_DB: finances_main
    POSTGRES_USER: finances_user_main
    POSTGRES_PASSWORD: "password"
    CI_SCHEMA_REPOSITORY: /tmp/ci_schema_repository


  before_script:
    - apk add --no-cache postgresql-dev postgresql-client openssh build-base git make nodejs sqlite sqlite-dev imagemagick tzdata

  script:
    - bash