stages:
  - pre-build
  - build
  - tests
  - cleanup

base image:
  stage: pre-build
  tags:
    - test-finances-shell

  script:
    - docker build --tag selenium:base .docker/Base
    - docker build --tag selenium:nodebase .docker/NodeBase
    - docker build --tag selenium:nodechrome .docker/NodeChrome
  when: manual

application image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag application:latest --file .docker/application.Dockerfile .

smoke:
  stage: tests
  image: application:latest
  services:
    - selenium:nodechrome
  tags:
    - test-finances-docker

  variables:
    APP_HOST: https://test-finances.404-group.info

  script:
    - cd /app && node_modules/protractor/bin/protractor conf.js --browser chrome --capabilities.chromeOptions.args headless --specs ./spec/panel/home_page.js

