stages:
  - pre-build
  - build
  - tests
  - cleanup

base image:
  stage: pre-build
  tags:
    - test-finances-shell

  script:
    - docker build --tag selenium:base .docker/Base
    - docker build --tag selenium:nodebase .docker/NodeBase
    - docker build --tag selenium:nodechrome .docker/NodeChrome
  when: manual

application image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag application:latest --file .docker/application.Dockerfile .

smoke:
  stage: tests
  image: application:latest
  tags:
    - test-finances-docker

  artifacts:
    paths:
      - app/

  before_script:
    - export TARGET_HOST=https://test-finances.404-group.info

  variables:
    APP_HOST: $TARGET_HOST

  script:
    - node_modules/protractor/bin/protractor conf.js --browser chrome  --capabilities.chromeOptions.args headless
