stages:
  - build
  - tests
  - cleanup

base image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag selenium:base --file .docker/Base/Dockerfile .
    - docker build --tag selenium:nodebase --file .docker/NodeBase/Dockerfile .
    - docker build --tag selenium:nodechrome --file .docker/NodeChrome/Dockerfile .
  when: manual

application image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag application:latest --file .docker/app.Dockerfile .
