stages:
  - build
  - tests
  - cleanup

base image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag selenium:base .docker/Base
    - docker build --tag selenium:nodebase .docker/NodeBase
    - docker build --tag selenium:nodechrome .docker/NodeChrome
  when: manual

application image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag application:latest --file .docker/app.Dockerfile .
