stages:
  - pre-build
  - build
  - tests
  - report

base image:
  stage: pre-build
  tags:
    - test-finances-shell

  script:
    - docker build --tag selenium:base .docker/Base
    - docker build --tag selenium:nodebase .docker/NodeBase
    - docker build --tag selenium:nodechrome .docker/NodeChrome
  when: manual

application image:
  stage: build
  tags:
    - test-finances-shell

  script:
    - docker build --tag application:latest --file .docker/application.Dockerfile .
  when: manual

smoke:
  stage: tests
  image: application:latest
  services:
    - selenium:nodechrome
  tags:
    - test-finances-docker

  variables:
    APP_HOST: https://test-finances.404-group.info

  script:
    - /node_modules/protractor/bin/protractor conf.js --suite preconditions,regression --browser chrome
    # TODO: after the fall of the tests you need to create a report anyway!!!
    - allure generate allure-results -o public --clean

  artifacts:
    paths:
      - public
    expire_in: 1 day

pages:
  stage: report
  tags:
    - test-finances-docker

  script:
    - ""

  artifacts:
    paths:
      - public
    expire_in: 1 day 

